# Generated by Django 4.2 on 2024-09-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0006_alter_history_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('heur', models.TimeField()),
                ('description', models.TextField()),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField()),
            ],
        ),
    ]
