# Generated by Django 5.1 on 2024-09-01 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0001_initial'),
        ('notification', '0002_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='lead',
        ),
        migrations.AddField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rendez.event'),
        ),
    ]
