# Generated by Django 4.2 on 2024-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_reminder_lead_reminder_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
