# Generated by Django 4.2 on 2024-09-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_reminder_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
