# Generated by Django 4.2 on 2024-09-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_lead_campaign'),
        ('communication', '0003_document_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lead.lead'),
        ),
    ]
