# Generated by Django 4.2 on 2024-09-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_lead_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='campaign',
        ),
    ]
