# Generated by Django 4.2 on 2024-09-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_lead_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='note',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type_interaction',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=10),
        ),
    ]
