# Generated by Django 4.2 on 2024-09-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_rename_note_interaction_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='raison',
            field=models.TextField(blank=True, null=True),
        ),
    ]
