# Generated by Django 5.1 on 2024-08-31 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPublicitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform', models.CharField(choices=[('Google Ads', 'Google Ads'), ('Facebook Ads', 'Facebook Ads')], default='Google Ads', max_length=100)),
                ('nom_entreprise', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
