# Generated by Django 4.2 on 2024-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_remove_lead_campaign'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypublicitaire',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='lead.lead'),
        ),
    ]
